CREATE TABLE candidate_round_progress (
    progress_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id INTEGER NOT NULL REFERENCES candidate_registration (registration_id),
    drive_round_id INTEGER NOT NULL REFERENCES hiring_drive_round (drive_round_id),
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    reporting_time TIMESTAMP WITH TIME ZONE,
    queued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    called_at TIMESTAMP WITH TIME ZONE,
    interview_started_at TIMESTAMP WITH TIME ZONE,
    interview_completed_at TIMESTAMP WITH TIME ZONE,
    result_decided_at TIMESTAMP WITH TIME ZONE,
    result_decided_by VARCHAR(100),
    status_changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status_changed_by VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_candidate_round_progress
        UNIQUE (registration_id, drive_round_id),
    CONSTRAINT ck_candidate_round_progress_status
        CHECK (status IN (
            'WAITING',
            'CALLED',
            'INTERVIEWING',
            'AWAITING_RESULT',
            'SELECTED',
            'REJECTED',
            'MISSED',
            'WITHDRAWN'
        )),
    CONSTRAINT ck_candidate_round_progress_call_details
        CHECK (
            status IN ('WAITING', 'WITHDRAWN')
            OR (reporting_time IS NOT NULL AND called_at IS NOT NULL)
        ),
    CONSTRAINT ck_candidate_round_progress_result_details
        CHECK (
            status NOT IN ('SELECTED', 'REJECTED')
            OR (result_decided_at IS NOT NULL AND result_decided_by IS NOT NULL)
        )
);

CREATE INDEX idx_candidate_round_progress_queue
    ON candidate_round_progress (drive_round_id, status, queued_at, progress_id);

CREATE INDEX idx_candidate_round_progress_registration
    ON candidate_round_progress (registration_id, status);
