CREATE TABLE company (
    company_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    contact_number VARCHAR(15) NOT NULL UNIQUE,
    job_description TEXT NOT NULL
);

CREATE TABLE interview_round (
    round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE student (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    contact_number VARCHAR(15) NOT NULL UNIQUE,
    resume BYTEA
);

CREATE TABLE company_custom_round (
    company_round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES company (company_id),
    round_id INTEGER NOT NULL REFERENCES interview_round (round_id),
    CONSTRAINT uk_company_round UNIQUE (company_id, round_id)
);

CREATE TABLE student_application (
    application_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES student (student_id),
    company_id INTEGER NOT NULL REFERENCES company (company_id),
    application_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_student_company_application UNIQUE (student_id, company_id)
);

CREATE TABLE student_round_selection (
    selection_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES student (student_id),
    company_round_id INTEGER NOT NULL REFERENCES company_custom_round (company_round_id),
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uk_student_company_round UNIQUE (student_id, company_round_id),
    CONSTRAINT ck_selection_status CHECK (status IN ('SELECTED', 'REJECTED', 'ON_HOLD'))
);
