CREATE TABLE application_user (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_application_user_username UNIQUE (username),
    CONSTRAINT ck_application_user_role CHECK (role IN ('ADMIN', 'RECRUITER'))
);
