CREATE TABLE candidate_round_schedule (
    schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES student (student_id),
    company_round_id INTEGER NOT NULL
        REFERENCES company_custom_round (company_round_id),
    reporting_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    notified_at TIMESTAMP WITH TIME ZONE,
    reported_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_candidate_round_schedule
        UNIQUE (student_id, company_round_id),

    CONSTRAINT ck_candidate_round_schedule_status
        CHECK (status IN (
            'SCHEDULED',
            'NOTIFIED',
            'REPORTED',
            'MISSED',
            'CANCELLED'
        ))
);

CREATE INDEX idx_candidate_round_schedule_reporting_time
    ON candidate_round_schedule (reporting_time);