CREATE TABLE hiring_drive (
    drive_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES company (company_id),
    drive_name VARCHAR(100) NOT NULL,
    venue VARCHAR(200) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    registration_token_hash VARCHAR(64) NOT NULL,
    token_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_hiring_drive_registration_token_hash
        UNIQUE (registration_token_hash),
    CONSTRAINT ck_hiring_drive_time_range
        CHECK (starts_at < ends_at),
    CONSTRAINT ck_hiring_drive_status
        CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE INDEX idx_hiring_drive_company
    ON hiring_drive (company_id);

CREATE INDEX idx_hiring_drive_status_starts_at
    ON hiring_drive (status, starts_at);
