CREATE TABLE hiring_drive_round (
    drive_round_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drive_id INTEGER NOT NULL REFERENCES hiring_drive (drive_id),
    company_round_id INTEGER NOT NULL REFERENCES company_custom_round (company_round_id),
    round_order INTEGER NOT NULL,

    CONSTRAINT uk_hiring_drive_round_assignment
        UNIQUE (drive_id, company_round_id),
    CONSTRAINT uk_hiring_drive_round_order
        UNIQUE (drive_id, round_order),
    CONSTRAINT ck_hiring_drive_round_order
        CHECK (round_order > 0)
);
