CREATE TABLE candidate_registration (
    registration_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_reference UUID NOT NULL,
    drive_id INTEGER NOT NULL REFERENCES hiring_drive (drive_id),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    contact_number VARCHAR(15),
    resume BYTEA,
    notification_channel VARCHAR(20) NOT NULL,
    notification_destination VARCHAR(100) NOT NULL,
    advance_notice_minutes INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uk_candidate_registration_reference
        UNIQUE (registration_reference),
    CONSTRAINT uk_candidate_registration_drive_email
        UNIQUE (drive_id, email),
    CONSTRAINT uk_candidate_registration_drive_contact
        UNIQUE (drive_id, contact_number),
    CONSTRAINT ck_candidate_registration_notification_channel
        CHECK (notification_channel IN ('SMS', 'EMAIL', 'WHATSAPP')),
    CONSTRAINT ck_candidate_registration_advance_notice
        CHECK (advance_notice_minutes BETWEEN 5 AND 240),
    CONSTRAINT ck_candidate_registration_status
        CHECK (status IN ('WAITING', 'CALLED', 'COMPLETED', 'WITHDRAWN'))
);

CREATE INDEX idx_candidate_registration_drive_status_registered
    ON candidate_registration (drive_id, status, registered_at);
